make whoami stuff JSON-ready

diff --git a/include/whoami b/include/whoami
--- a/include/whoami
+++ b/include/whoami
@@ -28,6 +28,17 @@ getWhoami(){
     printCsvHeader
     textTitle "0.0" "Show report generation info" "NOT_SCORED" "SUPPORT"
     textInfo "ARN: $CALLER_ARN  TIMESTAMP: $SCRIPT_START_TIME"
+  elif [[ "$MODE" == "json" ]]; then
+    CALLER_ARN_RAW=$($AWSCLI sts get-caller-identity --output json $PROFILE_OPT --region $REGION --query "Arn")
+    if [[ 255 -eq $? ]]; then
+      # Failed to get own identity ... exit
+      echo "ERROR WITH $PROFILE CREDENTIALS - EXITING!"
+      >&2 echo "ERROR WITH $PROFILE CREDENTIALS - EXITING!"
+      EXITCODE=2
+      exit $EXITCODE
+    fi
+    CALLER_ARN=$(echo $CALLER_ARN_RAW | tr -d '"')
+    textInfo "ARN: $CALLER_ARN  TIMESTAMP: $SCRIPT_START_TIME"    
   else
     echo ""
     echo -e " This report is being generated using credentials below:\n"
